services:
  mlflow_tests:
    build:
      context: ./mlflow_test
    container_name: mlflow_tests  
    environment:
      MLFLOW_TRACKING_URI: "http://mlflow:5000"
      EXPERIMENT_NAME: ${EXPERIMENT_NAME:-XGBoost_Experiment}
    # Run once and exit with pytest's status code
    command: ["pytest", "-q", "--maxfail=1", "--disable-warnings"]
