version: '3'

services:
  jupyter:
    build: ./jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebooks:/notebooks
      - ./datas:/notebooks/datas

  mlflow:
    build: ./mlflow
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./datas:/app/datas
      - ./mlruns:/app/mlruns 